//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.11
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


class IKVPPINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("IKVPSWIGNative", EntryPoint="SWIGRegisterExceptionCallbacks_IKVP")]
    public static extern void SWIGRegisterExceptionCallbacks_IKVP(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("IKVPSWIGNative", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_IKVP")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_IKVP(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_IKVP(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_IKVP(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(typeof(IKVPPINVOKE)) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(typeof(IKVPPINVOKE)) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("IKVPSWIGNative", EntryPoint="SWIGRegisterStringCallback_IKVP")]
    public static extern void SWIGRegisterStringCallback_IKVP(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_IKVP(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static IKVPPINVOKE() {
  }


  [global::System.Runtime.InteropServices.DllImport("IKVPSWIGNative", EntryPoint="CSharp_IKVPNode_GetFirstChild")]
  public static extern global::System.IntPtr IKVPNode_GetFirstChild(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("IKVPSWIGNative", EntryPoint="CSharp_IKVPNode_GetNextSibling")]
  public static extern global::System.IntPtr IKVPNode_GetNextSibling(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("IKVPSWIGNative", EntryPoint="CSharp_IKVPNode_GetValue")]
  public static extern int IKVPNode_GetValue(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("IKVPSWIGNative", EntryPoint="CSharp_new_IKVPNode")]
  public static extern global::System.IntPtr new_IKVPNode();

  [global::System.Runtime.InteropServices.DllImport("IKVPSWIGNative", EntryPoint="CSharp_delete_IKVPNode")]
  public static extern void delete_IKVPNode(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("IKVPSWIGNative", EntryPoint="CSharp_IKVPNode_director_connect")]
  public static extern void IKVPNode_director_connect(global::System.Runtime.InteropServices.HandleRef jarg1, IKVPNode.SwigDelegateIKVPNode_0 delegate0, IKVPNode.SwigDelegateIKVPNode_1 delegate1, IKVPNode.SwigDelegateIKVPNode_2 delegate2);

  [global::System.Runtime.InteropServices.DllImport("IKVPSWIGNative", EntryPoint="CSharp_new_KVPNode__SWIG_0")]
  public static extern global::System.IntPtr new_KVPNode__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("IKVPSWIGNative", EntryPoint="CSharp_new_KVPNode__SWIG_1")]
  public static extern global::System.IntPtr new_KVPNode__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("IKVPSWIGNative", EntryPoint="CSharp_delete_KVPNode")]
  public static extern void delete_KVPNode(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("IKVPSWIGNative", EntryPoint="CSharp_KVPNode_GetParent")]
  public static extern global::System.IntPtr KVPNode_GetParent(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("IKVPSWIGNative", EntryPoint="CSharp_KVPNode_GetParentSwigExplicitKVPNode")]
  public static extern global::System.IntPtr KVPNode_GetParentSwigExplicitKVPNode(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("IKVPSWIGNative", EntryPoint="CSharp_KVPNode_GetFirstChild")]
  public static extern global::System.IntPtr KVPNode_GetFirstChild(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("IKVPSWIGNative", EntryPoint="CSharp_KVPNode_GetFirstChildSwigExplicitKVPNode")]
  public static extern global::System.IntPtr KVPNode_GetFirstChildSwigExplicitKVPNode(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("IKVPSWIGNative", EntryPoint="CSharp_KVPNode_GetNextSibling")]
  public static extern global::System.IntPtr KVPNode_GetNextSibling(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("IKVPSWIGNative", EntryPoint="CSharp_KVPNode_GetNextSiblingSwigExplicitKVPNode")]
  public static extern global::System.IntPtr KVPNode_GetNextSiblingSwigExplicitKVPNode(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("IKVPSWIGNative", EntryPoint="CSharp_KVPNode_GetValue")]
  public static extern int KVPNode_GetValue(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("IKVPSWIGNative", EntryPoint="CSharp_KVPNode_GetValueSwigExplicitKVPNode")]
  public static extern int KVPNode_GetValueSwigExplicitKVPNode(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("IKVPSWIGNative", EntryPoint="CSharp_KVPNode_SetFirstChild")]
  public static extern void KVPNode_SetFirstChild(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("IKVPSWIGNative", EntryPoint="CSharp_KVPNode_SetNextSibling")]
  public static extern void KVPNode_SetNextSibling(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("IKVPSWIGNative", EntryPoint="CSharp_KVPNode_AddChild")]
  public static extern void KVPNode_AddChild(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("IKVPSWIGNative", EntryPoint="CSharp_KVPNode_director_connect")]
  public static extern void KVPNode_director_connect(global::System.Runtime.InteropServices.HandleRef jarg1, KVPNode.SwigDelegateKVPNode_0 delegate0, KVPNode.SwigDelegateKVPNode_1 delegate1, KVPNode.SwigDelegateKVPNode_2 delegate2, KVPNode.SwigDelegateKVPNode_3 delegate3);

  [global::System.Runtime.InteropServices.DllImport("IKVPSWIGNative", EntryPoint="CSharp_new_KVPAccessProviderForScanProtocol")]
  public static extern global::System.IntPtr new_KVPAccessProviderForScanProtocol();

  [global::System.Runtime.InteropServices.DllImport("IKVPSWIGNative", EntryPoint="CSharp_KVPAccessProviderForScanProtocol_Index")]
  public static extern void KVPAccessProviderForScanProtocol_Index(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("IKVPSWIGNative", EntryPoint="CSharp_KVPAccessProviderForScanProtocol_GetFirstChild")]
  public static extern global::System.IntPtr KVPAccessProviderForScanProtocol_GetFirstChild(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("IKVPSWIGNative", EntryPoint="CSharp_KVPAccessProviderForScanProtocol_GetFirstChildSwigExplicitKVPAccessProviderForScanProtocol")]
  public static extern global::System.IntPtr KVPAccessProviderForScanProtocol_GetFirstChildSwigExplicitKVPAccessProviderForScanProtocol(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("IKVPSWIGNative", EntryPoint="CSharp_KVPAccessProviderForScanProtocol_GetNextSibling")]
  public static extern global::System.IntPtr KVPAccessProviderForScanProtocol_GetNextSibling(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("IKVPSWIGNative", EntryPoint="CSharp_KVPAccessProviderForScanProtocol_GetNextSiblingSwigExplicitKVPAccessProviderForScanProtocol")]
  public static extern global::System.IntPtr KVPAccessProviderForScanProtocol_GetNextSiblingSwigExplicitKVPAccessProviderForScanProtocol(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("IKVPSWIGNative", EntryPoint="CSharp_KVPAccessProviderForScanProtocol_GetValue")]
  public static extern int KVPAccessProviderForScanProtocol_GetValue(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("IKVPSWIGNative", EntryPoint="CSharp_KVPAccessProviderForScanProtocol_GetValueSwigExplicitKVPAccessProviderForScanProtocol")]
  public static extern int KVPAccessProviderForScanProtocol_GetValueSwigExplicitKVPAccessProviderForScanProtocol(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("IKVPSWIGNative", EntryPoint="CSharp_delete_KVPAccessProviderForScanProtocol")]
  public static extern void delete_KVPAccessProviderForScanProtocol(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("IKVPSWIGNative", EntryPoint="CSharp_KVPAccessProviderForScanProtocol_director_connect")]
  public static extern void KVPAccessProviderForScanProtocol_director_connect(global::System.Runtime.InteropServices.HandleRef jarg1, KVPAccessProviderForScanProtocol.SwigDelegateKVPAccessProviderForScanProtocol_0 delegate0, KVPAccessProviderForScanProtocol.SwigDelegateKVPAccessProviderForScanProtocol_1 delegate1, KVPAccessProviderForScanProtocol.SwigDelegateKVPAccessProviderForScanProtocol_2 delegate2);

  [global::System.Runtime.InteropServices.DllImport("IKVPSWIGNative", EntryPoint="CSharp_ScanProtocol_GetData")]
  public static extern int ScanProtocol_GetData(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("IKVPSWIGNative", EntryPoint="CSharp_new_ScanProtocol")]
  public static extern global::System.IntPtr new_ScanProtocol();

  [global::System.Runtime.InteropServices.DllImport("IKVPSWIGNative", EntryPoint="CSharp_delete_ScanProtocol")]
  public static extern void delete_ScanProtocol(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("IKVPSWIGNative", EntryPoint="CSharp_ScanProtocol_director_connect")]
  public static extern void ScanProtocol_director_connect(global::System.Runtime.InteropServices.HandleRef jarg1, ScanProtocol.SwigDelegateScanProtocol_0 delegate0, ScanProtocol.SwigDelegateScanProtocol_1 delegate1, ScanProtocol.SwigDelegateScanProtocol_2 delegate2);

  [global::System.Runtime.InteropServices.DllImport("IKVPSWIGNative", EntryPoint="CSharp_KVPNode_SWIGUpcast")]
  public static extern global::System.IntPtr KVPNode_SWIGUpcast(global::System.IntPtr jarg1);

  [global::System.Runtime.InteropServices.DllImport("IKVPSWIGNative", EntryPoint="CSharp_KVPAccessProviderForScanProtocol_SWIGUpcast")]
  public static extern global::System.IntPtr KVPAccessProviderForScanProtocol_SWIGUpcast(global::System.IntPtr jarg1);

  [global::System.Runtime.InteropServices.DllImport("IKVPSWIGNative", EntryPoint="CSharp_ScanProtocol_SWIGUpcast")]
  public static extern global::System.IntPtr ScanProtocol_SWIGUpcast(global::System.IntPtr jarg1);
}
