//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.11
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class IKVPNode : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal IKVPNode(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IKVPNode obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~IKVPNode() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          IKVPPINVOKE.delete_IKVPNode(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public virtual IKVPNode GetFirstChild() {
    global::System.IntPtr cPtr = IKVPPINVOKE.IKVPNode_GetFirstChild(swigCPtr);
    IKVPNode ret = (cPtr == global::System.IntPtr.Zero) ? null : new IKVPNode(cPtr, false);
    return ret;
  }

  public virtual IKVPNode GetNextSibling() {
    global::System.IntPtr cPtr = IKVPPINVOKE.IKVPNode_GetNextSibling(swigCPtr);
    IKVPNode ret = (cPtr == global::System.IntPtr.Zero) ? null : new IKVPNode(cPtr, false);
    return ret;
  }

  public virtual int GetValue() {
    int ret = IKVPPINVOKE.IKVPNode_GetValue(swigCPtr);
    return ret;
  }

  public IKVPNode() : this(IKVPPINVOKE.new_IKVPNode(), true) {
    SwigDirectorConnect();
  }

  private void SwigDirectorConnect() {
    if (SwigDerivedClassHasMethod("GetFirstChild", swigMethodTypes0))
      swigDelegate0 = new SwigDelegateIKVPNode_0(SwigDirectorGetFirstChild);
    if (SwigDerivedClassHasMethod("GetNextSibling", swigMethodTypes1))
      swigDelegate1 = new SwigDelegateIKVPNode_1(SwigDirectorGetNextSibling);
    if (SwigDerivedClassHasMethod("GetValue", swigMethodTypes2))
      swigDelegate2 = new SwigDelegateIKVPNode_2(SwigDirectorGetValue);
    IKVPPINVOKE.IKVPNode_director_connect(swigCPtr, swigDelegate0, swigDelegate1, swigDelegate2);
  }

  private bool SwigDerivedClassHasMethod(string methodName, global::System.Type[] methodTypes) {
    global::System.Reflection.MethodInfo methodInfo = this.GetType().GetMethod(methodName, global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance, null, methodTypes, null);
    bool hasDerivedMethod = methodInfo.DeclaringType.IsSubclassOf(typeof(IKVPNode));
    return hasDerivedMethod;
  }

  private global::System.IntPtr SwigDirectorGetFirstChild() {
    return IKVPNode.getCPtr(GetFirstChild()).Handle;
  }

  private global::System.IntPtr SwigDirectorGetNextSibling() {
    return IKVPNode.getCPtr(GetNextSibling()).Handle;
  }

  private int SwigDirectorGetValue() {
    return GetValue();
  }

  public delegate global::System.IntPtr SwigDelegateIKVPNode_0();
  public delegate global::System.IntPtr SwigDelegateIKVPNode_1();
  public delegate int SwigDelegateIKVPNode_2();

  private SwigDelegateIKVPNode_0 swigDelegate0;
  private SwigDelegateIKVPNode_1 swigDelegate1;
  private SwigDelegateIKVPNode_2 swigDelegate2;

  private static global::System.Type[] swigMethodTypes0 = new global::System.Type[] {  };
  private static global::System.Type[] swigMethodTypes1 = new global::System.Type[] {  };
  private static global::System.Type[] swigMethodTypes2 = new global::System.Type[] {  };
}
