//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.11
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class ScanProtocol : KVPAccessProviderForScanProtocol {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal ScanProtocol(global::System.IntPtr cPtr, bool cMemoryOwn) : base(IKVPPINVOKE.ScanProtocol_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ScanProtocol obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ScanProtocol() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          IKVPPINVOKE.delete_ScanProtocol(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public int GetData() {
    int ret = IKVPPINVOKE.ScanProtocol_GetData(swigCPtr);
    return ret;
  }

  public ScanProtocol() : this(IKVPPINVOKE.new_ScanProtocol(), true) {
    SwigDirectorConnect();
  }

  private void SwigDirectorConnect() {
    if (SwigDerivedClassHasMethod("GetFirstChild", swigMethodTypes0))
      swigDelegate0 = new SwigDelegateScanProtocol_0(SwigDirectorGetFirstChild);
    if (SwigDerivedClassHasMethod("GetNextSibling", swigMethodTypes1))
      swigDelegate1 = new SwigDelegateScanProtocol_1(SwigDirectorGetNextSibling);
    if (SwigDerivedClassHasMethod("GetValue", swigMethodTypes2))
      swigDelegate2 = new SwigDelegateScanProtocol_2(SwigDirectorGetValue);
    IKVPPINVOKE.ScanProtocol_director_connect(swigCPtr, swigDelegate0, swigDelegate1, swigDelegate2);
  }

  private bool SwigDerivedClassHasMethod(string methodName, global::System.Type[] methodTypes) {
    global::System.Reflection.MethodInfo methodInfo = this.GetType().GetMethod(methodName, global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance, null, methodTypes, null);
    bool hasDerivedMethod = methodInfo.DeclaringType.IsSubclassOf(typeof(ScanProtocol));
    return hasDerivedMethod;
  }

  private global::System.IntPtr SwigDirectorGetFirstChild() {
    return IKVPNode.getCPtr(GetFirstChild()).Handle;
  }

  private global::System.IntPtr SwigDirectorGetNextSibling() {
    return IKVPNode.getCPtr(GetNextSibling()).Handle;
  }

  private int SwigDirectorGetValue() {
    return GetValue();
  }

  public delegate global::System.IntPtr SwigDelegateScanProtocol_0();
  public delegate global::System.IntPtr SwigDelegateScanProtocol_1();
  public delegate int SwigDelegateScanProtocol_2();

  private SwigDelegateScanProtocol_0 swigDelegate0;
  private SwigDelegateScanProtocol_1 swigDelegate1;
  private SwigDelegateScanProtocol_2 swigDelegate2;

  private static global::System.Type[] swigMethodTypes0 = new global::System.Type[] {  };
  private static global::System.Type[] swigMethodTypes1 = new global::System.Type[] {  };
  private static global::System.Type[] swigMethodTypes2 = new global::System.Type[] {  };
}
